---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: info
  data_bags_path: 'test/integration/data_bags'

platforms:
  - name: ubuntu-14.04
    driver:
        box: ubuntu-14.04.chef_client_12_7_2

suites:
  - name: default
    run_list:
      - recipe[chef-wrapper-mesos::master]
    driver:
      vm_hostname: 'default.local'
    attributes:
      datadog:
        api_key: '00000000000000000000000000000000'
        application_key: '0000000000000000000000000000000000000000'
      mesos:
        master:
          flags:
            cluster: 'mesos-home'
