name             'chef-wrapper-mesos'
maintainer       'Cobus Bernard'
maintainer_email 'me@cobus.io'
license          'MIT'
description      'Installs/Configures chef-wrapper-mesos'
long_description 'Installs/Configures chef-wrapper-mesos'
version          '0.1.8'

depends 'zookeeper-cluster', '~> 1.3.2'
depends 'mesos', '~> 3.5.1'
